export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";

export const SHOW_PAGE_LOADER = "APP/SHOW_PAGE_LOADER";
export const HIDE_PAGE_LOADER = "APP/HIDE_PAGE_LOADER";
export const SHOW_CONTENT_LOADER = "APP/SHOW_CONTENT_LOADER";
export const HIDE_CONTENT_LOADER = "APP/HIDE_CONTENT_LOADER";
